
* RETO 1. Normativa regional. Funciones y Limitaciones

** ¿Està realmente clara la normativa?

*** Respuesta

Sí. Está muy clara como se puede apreciar en la funcamentación

*** Fundamentación



/RESOLUCIÓN de 27 de junio de 2023, del secretario autonómico de Educación y Formación Profesional, por la que se aprueban las instrucciones para la organización y el funcionamiento de los centros que imparten Educación Infantil de segundo ciclo y Educación Primaria durante el curso 2023-2024. [2023/7350]/

/5.5.1. Persona coordinadora de las tecnologías de la información y comunicación (TIC)/

La persona coordinadora de las tecnologías de la información y comunicación (TIC) debe ejercer las tareas que se indican en el artículo 43.2 del Decreto 253/2019, de 29 de noviembre, del Consell, de regulación de la organización y el funcionamiento de los centros públicos que imparten enseñanzas de Educación Infantil o de Educación Primaria (DOGV 8689, 02.12.2019).


/DECRETO 253/2019, de 29 de noviembre, del Consell, de regulación de la organización y el funcionamiento de los centros públicos que imparten enseñanzas de Educación Infantil o de Educación Primaria. [2019/11482]/

/Artículo 43. Coordinadora o coordinador de las tecnologías de la información y comunicación/

1. La dirección del centro designará a la coordinadora o coordinador de las tecnologías de la información y comunicación (TIC), entre el profesorado del claustro, preferentemente entre los miembros con destino definitivo en el centro educativo y con formación y experiencia en el uso de las TIC, a propuesta de la dirección de estudios y oído el claustro. 

2. Las funciones de la coordinadora o coordinador de TIC serán:
    
   a) Coordinar el uso del aula o aulas de informática del centro. 

   b) Velar por el mantenimiento del material informático. 

   c) Ejercer la interlocución con el apoyo y la asistencia informática (SAI) así como con la administración, en los temas relativos a las TIC.  

   d) Gestionar, dentro de la aplicación de inventario TIC proporcionada por la administración, el hardware y el software de los que dispone el centro, que se responsabiliza de que esté localizado y disponible. 

   e) Colaborar en la confección del inventario del material informático no incluido en la aplicación de inventario TIC. 

   f) Promover y asesorar al claustro en la integración de las TIC en la tarea docente y su incorporación a la planificación didáctica y proyectos de innovación. 

   g) Asesorar en materia informática al resto del profesor
   ado e informar de las actividades que se lleven a cabo en el aula o aulas de informática. 

   h) Conocer, promover y asesorar a la comunidad educativa en el uso de las aplicaciones de gestión académica, administrativa y de comunicación que la Administración ponga al alcance de los centros educativos. 

   i) Conocer y asesorar a la comunidad educativa sobre la normativa y la ordenación reguladora del uso de las TIC en el centro. 

   j) Colaborar en el diseño del programa anual de formación del centro asesorando al claustro, y específicamente a la figura de la coordinación de formación, para realizar el análisis de las necesidades formativas del claustro en relación con el ámbito TIC. 

   k) Asesorar a la secretaría del centro en su función de atender y difundir los requisitos normativos para que el centro cumpla la normativa vigente en protección de datos en los procedimientos administrativos y, en la manera de compartir información mediante las tecnologías de la información y la comunicación. 

   l) Cualquier otra que la Administración educativa determine en su ámbito de competencias.

*** Fuente

https://portal.edu.gva.es/ctic/es/coordinacion-tic/#2.1


** ¿Conoces mejor tu ámbito de actuación?

Este ejercicio me ha servido para localizar la información y tenerla más a mano, aunque la conocía hacía tiempo que no la revisaba.

** ¿Se ha actualizado recientemente para recoger las últimas tendencias en las TIC?

Me parece que responde al objetivo que pretende abordar. Creo que poco a poco se va concretando la normativa propuesta por la Unión Europea. Aunque su implementación es lenta los diversos pasos que se van implementando creo que se realizan de manera bastante sólida.

** ¿Es lo suficientemente amplia como para no necesitar una revisión frecuente?

Creo que es suficientemente amplia, aunque los diferentes organismos que guian en su implemtación (AEPD, Conselleria, etc.) van concretando los contextos, sus funciones y limitaciones.

** ¿Hay algún punto que pueda ser conflictivo en cuanto a responsabilidades?

Por mi parte diría que la normativa es muy exigente, el trabajo de coordinación TIC es muy amplio, por lo que es difícil avanzar en el corto plazo.

